### ISSUE TITLE
 E/ActivityThread: Failed to find provider info for ipc_servicemanager

### ISSUE THREAD

**Issue by mf-00** [devyok/ServiceManager#2]
调用ServiceManager.init(getApplicationContext());时报错，

>  E/ActivityThread: Failed to find provider info for ipc_servicemanager
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IBinder.linkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
W/System.err:     at com.devyok.ipc.ServiceManager$RemoteServiceManagerProxy.create(ServiceManager.java:124)
W/System.err:     at com.devyok.ipc.ServiceManager.init(ServiceManager.java:37)

是按照说明步骤配置了classpath 'com.devyok.ipc:ipc-gradle-plugin:0.0.1'和implementation 'com.devyok.ipc:ipc-libcore:0.0.3'，后面的libcore试了0.0.1和0.0.2都不行。

**Comment by HaseebMalik22** [comment]
I resolved this issue by clearing the data on the application. Just go to Settings -> App Management -> (name of your application) -> Storage Usage -> Clear Data.
